AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito APIGATEWAY test

Parameters:
  ProjectName:
    Type: String
    Description: Proyecto Residentes para Tendencias de Arquitectura de Software
    Default: Residentes-Stack

Resources:
  CreateDocument:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/hello.zip
      FunctionName: !Sub "${ProjectName}-create_document"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /document
            Method: post
            RestApiId: !Ref ApiGatewayApi
  
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${ProjectName}-Documentos"
      PointInTimeRecoverySpecification: true
      PrimaryKey:
        Name: "id_documento"
        Type: String
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
        
Outputs:
  DocumentTableName:
    Description: Nombre de la tabla de documentos en DynamoDB
    Value: !Ref DocumentTable
  DocumentoApi:
    Description: "API Gateway endpoint URL para documentos"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
