AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito APIGATEWAY test

Parameters:
  ProjectName:
    Type: String
    Description: Proyecto Residentes para Tendencias de Arquitectura de Software
    Default: residentes
  Stage:
    Type: String
    Description: Stage of API GATEWAY
    Default: Prod
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "auth-api-${Stage}"
      StageName: !Ref Stage
      OpenApiVersion: '2.0'
      Description: API supporting the application
      TracingEnabled: true
      Variables:
        LAMBDA_ALIAS: !Ref Stage
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'OPTIONS,DELETE,GET,HEAD,POST,PUT'"
        AllowOrigin: "'*'"
      BinaryMediaTypes: 
          - "*/*"
  DeleteDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/delete_document.zip
      FunctionName: !Sub "${ProjectName}-delete_document"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
      Events:
        DeleteDocument:
          Type: Api
          Properties:
            Path: /document/{id_documento}
            Method: delete
            RestApiId: !Ref ApiGatewayApi
  UpdateDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/update_document.zip
      FunctionName: !Sub "${ProjectName}-update_document"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
      Events:
        UpdateDocument:
          Type: Api
          Properties:
            Path: /document/{id_documento}
            Method: put
            RestApiId: !Ref ApiGatewayApi
  CreateDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/create_document.zip
      FunctionName: !Sub "${ProjectName}-create_document"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
      Events:
        CreateDocument:
          Type: Api
          Properties:
            Path: /document
            Method: post
            RestApiId: !Ref ApiGatewayApi
  GetAllDocumentsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/get_all_documents.zip
      FunctionName: !Sub "${ProjectName}-get_all_documents"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PartiQLSelect'
              Resource: !GetAtt DocumentTable.Arn
      Events:
        GetAllDocuments:
          Type: Api
          Properties:
            Path: /document
            Method: get
            RestApiId: !Ref ApiGatewayApi
  FilterDocumentsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/filter_document.zip
      FunctionName: !Sub "${ProjectName}-filter_document"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:Scan'
              Resource: !GetAtt DocumentTable.Arn
      Events:
        FilterDocuments:
          Type: Api
          Properties:
            Path: /document/filter
            Method: get
            RestApiId: !Ref ApiGatewayApi
  SQSProviderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ProjectName}-sqs_provider.fifo"
      FifoQueue: true
      ContentBasedDeduplication: true  # Habilitar la deduplicación basada en el contenido
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/hello.zip
      FunctionName: !Sub "${ProjectName}-hello"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          SQS_NAME: !Ref SQSProviderQueue
      Policies:
      - Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt SQSProviderQueue.Arn
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ApiGatewayApi
  SQSConsumerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/sqs_consumer.zip
      FunctionName: !Sub "${ProjectName}-sqs_consumer"
      Handler: bootstrap
      Runtime: provided.al2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt SQSProviderQueue.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSProviderQueue.Arn
            BatchSize: 1
  FileUploadFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/image_upload.zip
      FunctionName: !Sub "${ProjectName}-image_upload"
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          BUCKET_NAME: !Ref DocumentBucket
          BUCKET_KEY: !Sub "documentos/"
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DocumentBucket
      Events:
        UploadFile:
          Type: Api 
          Properties:
            Path: /image_upload
            Method: post
            RestApiId: !Ref ApiGatewayApi
  FileReadFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/image_read.zip
      FunctionName: !Sub "${ProjectName}-image_read"
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          BUCKET_NAME: !Ref DocumentBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
      Events:
        ReadFile:
          Type: Api 
          Properties:
            Path: /image_read
            Method: get
            RestApiId: !Ref ApiGatewayApi
  DocumentTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "${ProjectName}-documentos"
      AttributeDefinitions:
        - AttributeName: id_documento
          AttributeType: S
      KeySchema:
        - AttributeName: id_documento
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "documentos-pdf"
      PublicAccessBlockConfiguration:
          BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - DELETE
              - HEAD
              - POST
              - PUT
            AllowedOrigins:
              - '*'
  DocumentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DocumentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 's3:GetObject'
            Effect: 'Allow'
            Principal: '*'
            Resource: !Sub '${DocumentBucket.Arn}/*'
          - Action: 's3:ListBucket'
            Effect: 'Allow'
            Principal: '*'
            Resource: !GetAtt DocumentBucket.Arn
Outputs:
  DocumentTableName:
    Description: Nombre de la tabla de documentos en DynamoDB
    Value: !Ref DocumentTable
  DocumentoApi:
    Description: "API Gateway endpoint URL para documentos"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
