AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito APIGATEWAY test

Parameters:
  ProjectName:
    Type: String
    Description: Proyecto Residentes para Tendencias de Arquitectura de Software
    Default: Residentes
  Stage:
    Type: String
    Description: Stage of API GATEWAY
    Default: Prod
Resources:
  CreateDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/create_document.zip
      FunctionName: !Sub "${ProjectName}-create_document"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
      Events:
        CreateDocument:
          Type: Api
          Properties:
            Path: /document
            Method: post
  GetAllDocumentsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/get_all_documents.zip
      FunctionName: !Sub "${ProjectName}-get_all_documents"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
            Actions:
              - dynamodb:PartiQLSelect
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
      Events:
        GetAllDocuments:
          Type: Api
          Properties:
            Path: /document
            Method: get
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/hello.zip
      FunctionName: !Sub "${ProjectName}-hello"
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /
            Method: get
  DocumentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${ProjectName}-documentos"
      PrimaryKey:
        Name: "id_documento"
        Type: String
Outputs:
  DocumentTableName:
    Description: Nombre de la tabla de documentos en DynamoDB
    Value: !Ref DocumentTable
  DocumentoApi:
    Description: "API Gateway endpoint URL para documentos"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
