AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cognito APIGATEWAY test

Parameters:
  ProjectName:
    Type: String
    Description: Proyecto Residentes para Tendencias de Arquitectura de Software
    Default: residentes
  Stage:
    Type: String
    Description: Stage of API GATEWAY
    Default: Prod
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "auth-api-${Stage}"
      StageName: !Ref Stage
      OpenApiVersion: '2.0'
      Description: API supporting the application
      TracingEnabled: true
      Variables:
        LAMBDA_ALIAS: !Ref Stage
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'DELETE, GET, HEAD, POST, PUT'"
        AllowOrigin: "'*'"
  CreateDocumentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/create_document.zip
      FunctionName: !Sub "${ProjectName}-create_document"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
      Events:
        CreateDocument:
          Type: Api
          Properties:
            Path: /document
            Method: post
            RestApiId: !Ref ApiGatewayApi
  GetAllDocumentsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/get_all_documents.zip
      FunctionName: !Sub "${ProjectName}-get_all_documents"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          TABLE_NAME: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PartiQLSelect'
              Resource: !GetAtt DocumentTable.Arn
      Events:
        GetAllDocuments:
          Type: Api
          Properties:
            Path: /document
            Method: get
            RestApiId: !Ref ApiGatewayApi
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/hello.zip
      FunctionName: !Sub "${ProjectName}-hello"
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ApiGatewayApi
  FileFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../bin/file.zip
      FunctionName: !Sub "${ProjectName}-file"
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          BUCKET_NAME: !Ref documentbucket
          BUCKET_KEY: !Sub "documentos/"
      Policies:
        - S3WritePolicy:
            BucketName: !Ref documentbucket
      Events:
        File:
          Type: Api 
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref ApiGatewayApi
  DocumentTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "${ProjectName}-documentos"
      AttributeDefinitions:
        - AttributeName: id_documento
          AttributeType: S
      KeySchema:
        - AttributeName: id_documento
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  documentbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "documentos-pdf"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - DELETE
              - HEAD
              - POST
              - PUT
            AllowedOrigins:
              - '*'
Outputs:
  DocumentTableName:
    Description: Nombre de la tabla de documentos en DynamoDB
    Value: !Ref DocumentTable
  DocumentoApi:
    Description: "API Gateway endpoint URL para documentos"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
